### ISSUE TITLE
Error with materialize.js while loading

### ISSUE THREAD

**Issue by elefantino** [jdanyow/aurelia-breeze-northwind#12]
I can't load this app due to the error:

Error: @http://localhost:9000/dist/resources/materialize.js:1:30
    @http://localhost:9000/dist/resources/materialize.js:1:1

```
Evaluating http://localhost:9000/dist/resources/materialize.js
Error loading http://localhost:9000/dist/resources/materialize.js
```

**Comment by johntom** [comment]
Hi,
If I had to guess it looks like as jspm or config issue. This is what I would do.
1 git clone this repo
2 npm install
3 npm install jspm --save-dev (makes it local)
4 .\node_modules.bin\jspm install
Test the results as this is what has worked for me.
John

**Comment by elefantino** [comment]
thanks, it works for me now

**Comment by johntom** [comment]
Did my suggestion work?
