### ISSUE TITLE
Cos/usage of the northwind API?

### ISSUE THREAD

**Issue by kristianmandrup** [jdanyow/aurelia-breeze-northwind#16]
I see you use http://sampleservice.breezejs.com/api/northwind as the endpoint. I wonder how you found the sample services on the breezejs site?

I managed to find northwind docs here http://northwind.servicestack.net/ and here http://docs.espressologic.com/docs/tutorial/northwind

and managed to retrieve list of Orders like this

`curl http://sampleservice.breezejs.com/api/northwind/orders`

Just in case others run into the same questions...

**Comment by jdanyow** [comment]
@wardbell generously offered the northwind breeze endpoint that's used in this project. At the time this project was created the API wasn't up to date with the latest breeze stuff so things like "include count" didn't work.
