### ISSUE TITLE
Uncaught Error loading "github:dogfalo/materialize@0.96.1

### ISSUE THREAD

**Issue by StefanScholte** [jdanyow/aurelia-breeze-northwind#2]
Hi there 
I followed the steps for running the app locally.

when I do a jspm install I get the following warning:
warn Main entry point not found for github:dogfalo/materialize@0.96.1.
     Adjust this property in the package.json or with an override, setting "main": false if this is the intention.

and when doing a gulp watch   the console shows the following error:

Uncaught Error loading "github:dogfalo/materialize@0.96.1" at http://localhost:9000/jspm_packages/github/dogfalo/materialize@0.96.1.js
Error loading "github:dogfalo/materialize@0.96.1" from "main" at http://localhost:9000/dist/main.js
Not Found: http://localhost:9000/jspm_packages/github/dogfalo/materialize@0.96.1.js

**Comment by jdanyow** [comment]
Hi @StefanScholte - I wasn't able to reproduce this- here's what I did to test it out:

``` shell
git clone https://github.com/jdanyow/aurelia-breeze-northwind
cd aurelia-breeze-northwind
npm install
jspm install
gulp watch
```

browse to localhost:9000... site loaded without issue.

**Comment by StefanScholte** [comment]
Hi @jdanyow,

I Just did exactly what you did to test it out and I'm still getting this error about Materialize.

what does "Main entry point not found for github:dogfalo/materialize@0.96.1.  Adjust this property in the package.json or with an override, setting "main": false if this is the intention." mean?
this is a warning I get when executing jspm install

and when I browse to localhost:9000 after gulp watch 
the console gives the following error:

"uncaught exception: Error loading "github:dogfalo/materialize@0.96.1" at http://localhost:9000/jspm_packages/github/dogfalo/materialize@0.96.1.js
Error loading "github:dogfalo/materialize@0.96.1" from "main" at http://localhost:9000/dist/main.js
Not Found: http://localhost:9000/jspm_packages/github/dogfalo/materialize@0.96.1.js
throw e;"

**Comment by KingRial** [comment]
Same errors here.

Still trying to figure why the materialize library won't be compiled.

**Comment by jdanyow** [comment]
Apologies for the issues- I'm looking into this right now.

**Comment by jdanyow** [comment]
Still can't reproduce, I'm on Windows- I'm going to try on a Mac.  Couple things to try:

Have you updated jspm lately?  `npm install jspm -g`

Try uninstalling and re-installing materialize:

``` bash
jspm uninstall materialize
jspm install materialize
```

**Comment by StefanScholte** [comment]
I did the above 
but I keep getting the error

Just for clarity,
The initial screen is visible with NorthWind and Breeze text and the spinner 
and then the error that is not finding this JS file:  http://localhost:9000/jspm_packages/github/dogfalo/materialize@0.96.1.js

**Comment by jdanyow** [comment]
can you share a screenshot of the console output?

**Comment by StefanScholte** [comment]
![snapshot1_installing materialize](https://cloud.githubusercontent.com/assets/10086538/7898820/062f0796-070d-11e5-877b-e10b7c6f48b6.png)
![snapshot2_webpage_started_localhost](https://cloud.githubusercontent.com/assets/10086538/7898821/0c92b24a-070d-11e5-8ad0-c61fbc06e6cb.png)

**Comment by fopsdev** [comment]
same here, i'm on ubuntu
![screenshot - 310515 - 12 16 46](https://cloud.githubusercontent.com/assets/5448300/7901735/0347f1aa-078f-11e5-9ac7-e8743ef198c2.png)

**Comment by jdanyow** [comment]
Another thing to try:

https://github.com/aurelia/skeleton-navigation/issues/65#issuecomment-101042305

```
jspm cc
jspm install
```

**Comment by fopsdev** [comment]
did not work for me. same error.
did a reinstall of jspm using npm install
then deleted jspm_modules folder
then ran the above commands

**Comment by StefanScholte** [comment]
Nope did not work for me too.

**Comment by KingRial** [comment]
Here how I solved the problem on my machine:

```
jspm cc
Removing directory "jspm_packages" from the root directory
jspm install
```

For some reasons, if jspm fails some operation, it won't compile correctly all the environment and it will think that everything is correct.

Removing the directory after the cache clear operation, should solve the problem

P.S. on windows: remember to use a command shell with the rights to access your user directory. To be sure, start a command shell with administration privileges.

**Comment by aguspiza** [comment]
after:

jspm uninstall materialize
jspm install materialize

it worked but i got 2 folders inside jspm_packages/github with different casing:
Dogfalo and dogfalo

it seems that it is Dogfalo at github. Linux is case sensitive so that is why it does work on Windows.

**Comment by jdanyow** [comment]
thanks @aguspiza !

**Comment by StefanScholte** [comment]
Thanks you guys 
it works very good now
