### ISSUE TITLE
thx this is great, But

### ISSUE THREAD

**Issue by Martin-Andersen** [jdanyow/aurelia-breeze-northwind#3]
thx nice example.

I am looking for a way to do the same in VS2015, can you provide a guide or give me a hint to get started with Aurelia in VS2015 deployed to IIS

**Comment by cmichaelgraham** [comment]
hi @Martin-Andersen - you can take a look at [aurelia-typescript samples](https://github.com/cmichaelgraham/aurelia-typescript#aurelia-typescript) which show VS 2013 and Aurelia using a bundle (this is somewhat dated)

you can also look at the TS 15 port (located on a branch), for more up to date versions: [aurelia-typescript TS 15 samples](https://github.com/cmichaelgraham/aurelia-typescript/tree/typescript-1-5-port)

it is on my backlog to port this sample into VS / TS15 and to show it in VS code, 2013, and 2015, but i've been a bit slowed down by a job change, so it is a little ways off.
